name: protienTracker
description: A protein tracker that uses AngularDart Components
# version: 1.0.0
# author: Celie Baker <celie.n133@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
